title: Jie Xu # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of Social Policy and Data Analytics
  <br><br>
  University of Pennsylvania 
  <br><br>
  <a href="https://www.linkedin.com/in/jie-xu-0b0a541a4/">View My LinkedIn Profile</a>  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
